### PR TITLE
Collaborative Cleanup

### PR DESCRIPTION
**Pull request by cloudRoutine**
since we can both commit on an open PR we can probably work through the kinks faster like this if you want

### CODE REVIEW

**Comment by majocha** [comment]
I was actually thinking how to proceed best with it.

As for now I'd like to  branch out adding navigation to all the entities into a separate PR. All the work with it is simple and tedious but it's all in FSharp.LanguageService.Compiler so I'd like to keep the diff as minimal as possible if something goes wrong =)

We have overlap only with this one file. It's OK if you just take and modify it freely in your PR because the only thing I'm going to touch is the WPF stuff. The navigation stuff in this file is nicely separated so it shouldn't be a problem at all.

**Comment by cloudRoutine** [comment]
Cool i'll keep trying to polish up the nav and i'll PR that later, good working with you 👍

**Comment by majocha** [comment]
Think about integrating the "go to metadata", please :)

**Comment by cloudRoutine** [comment]
I suspect something will come to me once I start digging into NicePrint for the generation

**Pull request merged**
